all: comp run

pv:  comp_pv run_pv

pa: comp_pa run_pa

comp:
	gcc index.c -o main

run:
	./main

comp_pv:
	gcc view_p.c -o view_p

run_pv:
	.\view_p.exe


comp_pa:
	gcc about.c -o about

run_pa:
	.\about.exe
